
CREATE TABLE alchemist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT,
    gold DOUBLE PRECISION,
    CONSTRAINT pk_alchemist PRIMARY KEY (id)
);

CREATE TABLE inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alchemist_id BIGINT UNIQUE NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (id),
    CONSTRAINT fk_inventory_alchemist_id FOREIGN KEY (alchemist_id)
        REFERENCES alchemist(id)
);

CREATE TABLE ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT,
    description TEXT,
    value DOUBLE PRECISION,
    CONSTRAINT pk_ingredient PRIMARY KEY (id)
);

CREATE TABLE inventory_ingredient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    CONSTRAINT pk_inventory_ingredient PRIMARY KEY (id),
    CONSTRAINT fk_inventory_ingredient_inventory_id FOREIGN KEY (inventory_id) REFERENCES inventory(id),
    CONSTRAINT fk_inventory_ingredient_ingredient_id FOREIGN KEY (ingredient_id) REFERENCES ingredient(id),
    CONSTRAINT uq_inventory_ingredient UNIQUE (inventory_id, ingredient_id)
);

